require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project './refAppCommon.xcodeproj'

target 'refAppCommon' do
  platform :ios, '12.0'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'refAppCommonUITests' do
    inherit! :complete
    # Pods for testing
  end
end

#RN 0.67.4 does not support TVOS
# target 'refAppCommon-tvOS' do
#   platform :tvos, '12.0'

#   # Pods for refAppCommon-tvOS
# 	config = use_native_modules!
  
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # to enable hermes on iOS, change `false` to `true` and then install pods
#     :hermes_enabled => false
#   )

#   target 'refAppCommon-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['DEVELOPMENT_TEAM'].nil?
        config.build_settings['DEVELOPMENT_TEAM'] = 'QK7L23LPTC'
      end
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      if config.build_settings['TVOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

      #####
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          #config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.4'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION', 'FOLLY_HAVE_CLOCK_GETTIME=1']
        end
      end

#####

    end
  end
end
