require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'

project './unifiedExample.xcodeproj'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'unifiedExample' do
  config = use_native_modules!
  platform :ios, '13.0'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # target 'unifiedExampleTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

end

target 'unifiedExample-tvOS' do
  config = use_native_modules!
  platform :tvos, '13'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # target 'unifiedExample-tvOSTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

end

post_install do |installer|
  `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_13_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['DEVELOPMENT_TEAM'].nil?
        config.build_settings['DEVELOPMENT_TEAM'] = 'QK7L23LPTC'
      end
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      if config.build_settings['TVOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '12.0'
      end

      #####
case target.name
when 'RCT-Folly'
  target.build_configurations.each do |config|
    #config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.4'
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION', 'FOLLY_HAVE_CLOCK_GETTIME=1']
  end
else
  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
end

#####

    end
  end
end
